// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter that uses cookies only (no localStorage)
// Cookies ensure runtime updates are saved and persist across sessions
const cookieStorageAdapter = {
  getItem: (key: string): string | null => {
    try {
      // Use cookies only
      return getCookie(key);
    } catch (error) {
      console.error('[CookieStorage] Error getting item:', error);
      return null;
    }
  },
  
  setItem: (key: string, value: string): void => {
    try {
      // Store in cookies only (runtime updates will be saved)
      setCookie(key, value, 7); // 7 days expiry
      console.log('[CookieStorage] Session stored in cookie:', key);
    } catch (error) {
      console.error('[CookieStorage] Error setting item:', error);
    }
  },
  
  removeItem: (key: string): void => {
    try {
      // Remove from cookie only
      deleteCookie(key);
      console.log('[CookieStorage] Session removed from cookie:', key);
    } catch (error) {
      console.error('[CookieStorage] Error removing item:', error);
    }
  },
};

// Cookie helper functions
function setCookie(name: string, value: string, days: number): void {
  try {
    const expires = new Date();
    expires.setTime(expires.getTime() + days * 24 * 60 * 60 * 1000);
    // Use Secure flag in production (HTTPS), SameSite=Lax for CSRF protection
    const isSecure = window.location.protocol === 'https:';
    const cookieString = `${name}=${encodeURIComponent(value)};expires=${expires.toUTCString()};path=/;SameSite=Lax${isSecure ? ';Secure' : ''}`;
    document.cookie = cookieString;
  } catch (error) {
    console.error('[CookieStorage] Error setting cookie:', error);
  }
}

function getCookie(name: string): string | null {
  try {
    const nameEQ = name + "=";
    const ca = document.cookie.split(';');
    for (let i = 0; i < ca.length; i++) {
      let c = ca[i];
      while (c.charAt(0) === ' ') c = c.substring(1, c.length);
      if (c.indexOf(nameEQ) === 0) {
        return decodeURIComponent(c.substring(nameEQ.length, c.length));
      }
    }
    return null;
  } catch (error) {
    console.error('[CookieStorage] Error getting cookie:', error);
    return null;
  }
}

function deleteCookie(name: string): void {
  try {
    document.cookie = `${name}=;expires=Thu, 01 Jan 1970 00:00:00 UTC;path=/;`;
  } catch (error) {
    console.error('[CookieStorage] Error deleting cookie:', error);
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorageAdapter,
    persistSession: true,
    autoRefreshToken: true,
  }
});


